---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: "Update apt cache"
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600

  roles:
    - role: genlab.common.swapfile
      swapfile_path: /swapfile
      swapfile_size_mb: 2000
      swapfile_swappiness: 30
      swapfile_state: present
      swapfile_test_mode: true
