---
- name: "Install | Create Grafana system user"
  ansible.builtin.user:
    name: grafana
    system: true
    shell: "/sbin/nologin"
    create_home: false
    state: present

- name: "Install | Install Grafana"
  block:
    - name: "Install | Check Grafana version"
      changed_when: false
      ansible.builtin.command:
        cmd: "grafana-server --version"
      register: grafana_ver

    - name: "Install | Assert version correctness"
      ansible.builtin.assert:
        that: "grafana_ver.stdout is regex('{{ grafana_version }}')"
        success_msg: "grafana version {{ grafana_version }} is installed and working"
        fail_msg: "grafana version {{ grafana_version }} is not installed or not working correctly"

  rescue:
    - name: "Install | Ensure that directories exist"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ grafana_user }}"
        group: "{{ grafana_group }}"
        mode: '0775'
      with_items:
        - "{{ grafana_log_dir }}"
        - "{{ grafana_data_dir }}"
        - "{{ grafana_plugins_dir }}"

    - name: "Install | Download Grafana .deb package"
      ansible.builtin.get_url:
        url: "https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_amd64.deb"
        dest: "/tmp/grafana-{{ grafana_version }}_amd64.deb"
        owner: "{{ grafana_user }}"
        group: "{{ grafana_group }}"
        mode: "0644"
      register: grafana_package_tmp

    - name: "Install | Install .deb package"
      notify: "(Re)start and enable Grafana"
      ansible.builtin.apt:
        deb: "{{ grafana_package_tmp.dest }}"
        state: present
        update_cache: true

    - name: "Install | Cleanup downloads"
      ansible.builtin.file:
        path: "/tmp/grafana-{{ grafana_version }}_amd64.deb"
        state: absent

    - name: "Install | Create a .env file for systemd service unit"
      notify: "(Re)start and enable Grafana"
      ansible.builtin.template:
        src: grafana-server.env.j2
        dest: "{{ item }}"
        owner: "{{ grafana_user }}"
        group: "{{ grafana_group }}"
        mode: "0660"
      with_items:
        - "/etc/default/grafana-server"
        - "/etc/default/grafana"

- name: "Flush handlers"
  ansible.builtin.meta: "flush_handlers"
