---
- name: "Reset default admin password"
  no_log: "{{ grafana_no_log_secrets }}"
  changed_when: false
  ansible.builtin.command: >
    grafana-cli admin reset-admin-password "{{ admin_api_password }}"
- name: "Users | Update a Grafana user"
  no_log: "{{ grafana_no_log_secrets }}"
  community.grafana.grafana_user:
    state: present
    name: "{{ user.name }}"
    email: "{{ user.user_email }}"
    login: "{{ user.user_login }}"
    password: "{{ user.user_password }}"
    is_admin: "{{ user.is_admin | default(false) }}"
    url: "http://127.0.0.1:{{ grafana_port }}"
    url_username: "{{ admin_api_username }}"
    url_password: "{{ admin_api_password }}"
