---
samba:
  users:
    - name: smb
      id: 9000
      password: "12345"
      comment: ""
      state: present
      primary: true
  shares:
    - name: test
      browsable: true
      readonly: false
      guestok: false
      validusers:
        - smb
      writelist:
        - smb
