network:
  server:
    private_key: ...
    public_key: ...
    port: 51820
  allowed_ip: 10.0.0.1/32

peers:
  - username: test
    machine: none
    state: present
    private_key: ...
    public_key: ...
    preshared_key: ...
    ip_address: 10.0.0.2/32
    ports: [445]
