---
smartctl_exporter_web_listen_address: "localhost:9633"
smartctl_exporter_args: ""
smartctl_exporter_version: "0.14.0"
smartctl_exporter_config_dir: "/etc/exporters"
smartctl_exporter_interval: "60s"
smartctl_exporter_rescan: "10m"
smartctl_exporter_devices: []
smartctl_exporter_device_exclude: ""
smartctl_exporter_device_include: ""
smartctl_exporter_web_telemetry_path: "/metrics"
smartctl_exporter_log_level: "info"
smartctl_exporter_log_format: "logfmt"
