---
galaxy_info:
  role_name: "sftp_share"
  namespace: genlab
  author: "Sergey Malyuk"
  company: "Genlab, LLC"
  description: ""
  license: "MIT"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: [ "focal", "jammy", "noble" ]

  galaxy_tags: [ ]

dependencies: []
