---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # https://github.com/ansible/molecule/issues/3587#issuecomment-1158650179
    - name: "Include default vars"
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions: ['yml']

    # kics-scan ignore-block - kics doesn't like HTTP but on localhost it's not important
    - name: "Sanity check the Promtail daemon"
      retries: 3
      delay: 1
      register: promtail_this
      failed_when: "promtail_this.content != 'Ready'"
      ansible.builtin.uri:
        url: "http://localhost:{{ promtail_http_port }}/ready"
        return_content: true
