# kics-scan-disable=2e8d4922-8362-4606-8c14-aa10466a1ce3
---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true

  tasks:
    - name: "Sanity check the node exporter"
      retries: 5
      delay: 1
      register: node_exporter_check
      failed_when: '"node_exporter_build_info" not in node_exporter_check.content'
      ansible.builtin.uri:
        url: "http://localhost:9100/metrics"
        return_content: true
