---
- name: "Mount devices"
  loop: "{{ mount_device_devices }}"
  ansible.posix.mount:
    fstype: "{{ item.fstype }}"
    path: "{{ item.where }}"
    src: "{{ item.what }}"
    opts: "{{ item.opts | join(',') }}"
    state: "{{ item.state }}"
