---
galaxy_info:
  role_name: "uptime_kuma"
  namespace: genlab
  author: "Alexander Gorelyshev"
  company: "Genlab, LLC"
  description: ""
  license: "MIT"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["focal", "jammy"]

  galaxy_tags: []

dependencies: []
