apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    basicAuth: false
    basicAuthPassword: false
    url: http://localhost:3100
    jsonData:
      maxLines: 1000
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: "Bearer your_token_here"
    version: 1
    editable: false
