---
- name: Converge
  hosts: all
  roles:
    - role: genlab.common.wg_spoke
      wg_spoke_iface_name: adm
      wg_spoke_subnet: "10.0.0.0"
      wg_spoke_netmask: "24"
      wg_spoke_spoke_ipv4_vpn: "10.0.0.1"
      wg_spoke_spoke_port: "51820"
      wg_spoke_spoke_pkey: eGqGx4A5ufFKatLflPFKNuzFgGuospIe08iPbTlEhm0=
      wg_spoke_hub_pubkey: EvcoZ21/p0AHz5y95jwjVIR9puljc2kXqh/f3U1A4nk=
      # wg_spoke_hub_psk: 5qmMuLuGQT7w8VnHPsZDO4vRF5wEKcpEtaCQW1BLmbg=
      wg_spoke_hub_ipv4_wan: "1.2.3.4"
      wg_spoke_hub_ipv4_vpn: "10.0.0.254"
      wg_spoke_hub_port: "51820"
      wg_spoke_dns_server: "10.0.0.254:5300"
      wg_spoke_domain: "adm.local"
      wg_spoke_hide_secrets: false
      wg_spoke_logging: false  # doesn't work in Github Actions environment
