---
- name: Verify
  hosts: all
  gather_facts: false
  any_errors_fatal: true
  vars:
    wg_spoke_iface_name: adm

  tasks:
    - name: "Check that the Wireguard service is running"
      ansible.builtin.service:
        name: wg-quick@{{ wg_spoke_iface_name }}
        state: started
