---

- name: "Deploy | spin-up the server container via docker compose"
  tags: [samba-srv, samba-srv-deploy]
  changed_when: false
  community.docker.docker_compose_v2:
    project_src: "{{ smb_compose_path }}"
    build: always
    state: present
    recreate: always
