---
# tasks file for playbooks/roles/samba_crazymax

- name: "Include variable preparation tasks"
  ansible.builtin.include_tasks: prepare.yaml
  tags: [samba-srv, samba-srv-prepare]

- name: "Include installation tasks"
  ansible.builtin.include_tasks: install.yaml
  tags: [samba-srv, samba-srv-install]

- name: "Include configuration tasks"
  ansible.builtin.include_tasks: configure.yaml
  tags: [samba-srv, samba-srv-configure]

- name: "Include deployment tasks"
  ansible.builtin.include_tasks: deploy.yaml
  tags: [samba-srv, samba-srv-deploy]
