galaxy_info:
  role_name: xfs_project_quotas
  namespace: genlab
  author: Alexander Gorelyshev
  company: Genlab, LLC
  description: ""
  license: GPL-2.0-or-later
  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions: ["jammy", "noble"]

  galaxy_tags: []

dependencies: []
