---
ipmi_exporter_version: 1.10.1
ipmi_exporter_config_dir: "/etc/ipmi_exporter"
ipmi_exporter_log_level: "info"
ipmi_exporter_log_format: "logfmt"
ipmi_exporter_web_listen_address: "0.0.0.0:9290"
ipmi_exporter_args: ""
