---
ipmi_exp_version: 1.10.1
ipmi_exp_dir: "/etc/exporters"
ipmi_exp_config_dir: "/etc/exporters/config"
ipmi_exp_log_level: "info"
ipmi_exp_log_format: "logfmt"
ipmi_exp_web_listen_address: "localhost:9290"
ipmi_exp_args: ""
