galaxy_info:
  role_name: users
  namespace: genlab
  author: Alexander Gorelyshev
  company: Genlab, LLC
  description: Deploy user accounts
  license: GPL-2.0-or-later
  min_ansible_version: "2.1"

  platforms:
    - name: Ubuntu
      versions: [ "focal", "jammy", "noble" ]

  galaxy_tags: []

dependencies: []
