---
galaxy_info:
  role_name: perccli
  namespace: genlab
  author: "Alexander Gorelyshev"
  company: "Genlab, LLC"
  description: "Install perccli tool for Dell HBA and RAID adapters."
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["jammy", "noble"]

dependencies: []
