galaxy_info:
  role_name: promtail
  namespace: genlab
  author: Danilkin Danila
  description: Installs Promtail

  company: Genlab LLC
  license: MIT

  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["jammy", "noble"]

  galaxy_tags: []

dependencies: []
