---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # Blank task for ignoring CI testing, because there is no normal way to download
    # server64_with_all_clients_8_3_26_1540.zip inside github actions
    # This role was tested manually
    - name: Blank
      ansible.builtin.command: echo
      changed_when: false

    # - name: "Get 1C version"
    #   register: platform1c_version_installed
    #   changed_when: false
    #   ansible.builtin.command:
    #     cmd: "ls /opt/1cv8/x86_64"

    # - name: Read 1C version
    #   ansible.builtin.debug:
    #     msg: "{{ platform1c_version_installed.stdout }}"
