---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "Get 1C version"
      register: platform1c_version_installed
      changed_when: false
      ansible.builtin.command:
        cmd: "ls /opt/1cv8/x86_64"

    - name: Read 1C version
      ansible.builtin.debug:
        msg: "{{ platform1c_version_installed.stdout }}"
