---
galaxy_info:
  role_name: "borg_server"
  namespace: genlab
  author: "Alexander Gorelyshev"
  company: "Genlab, LLC"
  description: "Set up Borg repository(-ies) "
  license: "MIT"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["jammy", "noble"]

  galaxy_tags: []

dependencies: []
