---
- name: "Upload smartctl_exporter local configure file"
  notify: "(Re)start and enable smartctl_exporter"
  when: smartctl_exp_source_web_config_dir is defined and smartctl_exp_source_web_config_dir | length > 0
  ansible.builtin.template:
    src: "{{ smartctl_exp_source_web_config_dir }}/web_smartctl.conf"
    dest: "{{ smartctl_exporter_web_config_dir }}/web_smartctl.conf"
    owner: root
    group: root
    mode: '0640'
