---
galaxy_info:
  role_name: "mkfs"
  author: "Alexander Gorelyshev"
  company: "Genlab, LLC"
  namespace: genlab
  description: "Create a filesystem on a target device"
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["jammy", "noble"]

  galaxy_tags: []

dependencies: []
