# tasks file
---

- name: "Include installation tasks"
  ansible.builtin.include_tasks: "install.yaml"

- name: "Include configuration tasks"
  ansible.builtin.include_tasks: "configure.yaml"

- name: "Include run tasks"
  ansible.builtin.include_tasks: "run.yaml"
