---
galaxy_info:
  role_name: mount_device
  namespace: genlab
  author: "Alexander Gorelyshev"
  company: "Genlab, LLC"
  description: "Mount the given device"
  license: "GPL-2.0-or-later"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["jammy", "noble"]

  galaxy_tags: []

dependencies: []
