---
- name: Converge
  hosts: all
  roles:
    - role: genlab.common.docker_ubuntu
      docker_ubuntu_version: "27.3.1"
      docker_ubuntu_registry_mirrors:
        - https://docker.io
        - https://mirror.gcr.io
