---
uptime_kuma_img_version: "1.23.16-alpine"
uptime_kuma_project_dir: "/uptime-kuma"
uptime_kuma_port: 3001
uptime_kuma_api_version: "1.2.0"
uptime_kuma_limit_cpus: 2
uptime_kuma_limit_ram: "2G"
uptime_kuma_default_notification_names: []
