---
galaxy_info:
  role_name: "rustdesk"
  namespace: genlab
  author: "Sergey Malyuk"
  company: "Genlab, LLC"
  description: ""
  license: "MIT"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["jammy", "noble"]

  galaxy_tags: []

dependencies: []
