---
grafana_user: "grafana"
grafana_group: "grafana"
grafana_version: "12.3.1"
grafana_port: 3000
grafana_dashboard_dir: "/tmp/grafana/dashboards"
grafana_plugins_dir: "/var/lib/grafana/plugins"
grafana_datasource_dir: "/etc/grafana/provisioning/datasources"
grafana_log_dir: "/var/log/grafana"
grafana_data_dir: "/var/lib/grafana"
grafana_no_log_secrets: true
