---
galaxy_info:
  role_name: loki
  namespace: genlab
  author: "Danila Danilkin"
  company: "Genlab, LLC"
  description: "Deploy Loki as a systemd service"
  license: "MIT"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: ["jammy", "noble"]

  galaxy_tags: []

dependencies: []
