---
galaxy_info:
  role_name: docker_ubuntu
  namespace: genlab
  author: "Alexander Gorelyshev"
  company: "Genlab, LLC"
  description: "Install Docker ecosystem on Ubuntu"
  license: "MIT"
  min_ansible_version: "2.1"

  platforms:
    - name: "Ubuntu"
      versions: [ "focal", "jammy", "noble" ]

  galaxy_tags: [ "docker" ]

dependencies: []
