---
prometheus_version: 3.2.1
prometheus_dir: "/etc/prometheus"
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_config_dir: "/etc/prometheus/conf"
prometheus_db_dir: "/var/lib/prometheus"
