- name: "Set fact for daemon_reload"
  ansible.builtin.set_fact:
    metr1c_daemon_reload_required: "{{ metr1c_service.changed | bool }}"

- name: "Make sure that the metr1c service is started"
  become: true
  ansible.builtin.systemd:
    name: "metr1c.service"
    state: started
    enabled: true
    daemon_reload: "{{ metr1c_daemon_reload_required }}"
