---
- name: "Install Wireguard system-wide"
  ansible.builtin.apt:
    name: wireguard
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Ensure no dashes in the interface name"
  when: "'-' in wg_spoke_iface_name"
  ansible.builtin.fail:
    msg: "The interface name must not contain dashes, got: '{{ wg_spoke_iface_name }}'"

- name: "Create a Spoke configuration file"
  no_log: "{{ wg_spoke_hide_secrets }}"
  notify: "Run the Wireguard service"
  ansible.builtin.blockinfile:
    path: "/etc/wireguard/{{ wg_spoke_iface_name }}.conf"
    create: true
    owner: root
    group: root
    mode: "0600"
    state: present
    block: |
      [Interface]  # Local settings for this node
      Address = {{ wg_spoke_spoke_ipv4_vpn }}/32
      ListenPort = {{ wg_spoke_spoke_port }}
      PrivateKey = {{ wg_spoke_spoke_pkey }}

      {% if wg_spoke_dns_server is defined and wg_spoke_domain is defined %}
      PostUp = resolvectl dns %i {{ wg_spoke_dns_server }}; resolvectl domain %i {{ wg_spoke_domain }}
      {% endif %}

      [Peer]  # Settings for the Hub peer
      PublicKey = {{ wg_spoke_hub_pubkey }}
      {% if spoke_psk is defined %}
      PresharedKey = {{ spoke_psk }}
      {% endif %}
      AllowedIPs = {{ wg_spoke_subnet }}/{{ wg_spoke_netmask }}
      Endpoint = {{ wg_spoke_hub_ipv4_wan }}:{{ wg_spoke_hub_port }}
      PersistentKeepalive = 20
