---
- name: "Include Wireguard deployment tasks"
  ansible.builtin.include_tasks:
    file: "tasks/deploy.yml"

- name: "Include Wireguard logging configuration tasks"
  when: wg_spoke_logging is true
  ansible.builtin.include_tasks:
    file: "tasks/logging.yml"
