---
name: kics

on:
  pull_request:
    
jobs:
  kics:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
        name: Check out source code

      - name: run a KICS scan
        uses: checkmarx/kics-github-action@63fca4ca72e56edbb5a599ee756e6af1fdb1e785
        with:
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: myResults/
