---
name: kics

on:
  pull_request:
    
jobs:
  kics:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6
        name: Check out source code

      - name: run a KICS scan
        uses: checkmarx/kics-github-action@00def9108246ec656aea725db2167522d26a99d2
        with:
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}
          output_path: myResults/
