---
name: linters

on:
  pull_request:

jobs:

  ansible-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v6

      - uses: mamba-org/setup-micromamba@6a5f0547928ada1027cc3431afd6acd82ce56163
        with:
          micromamba-version: '2.4.0-0'
          environment-file: ci/conda.yml
          init-shell: bash
          post-cleanup: 'all'
          cache-environment: true

      - name: Check workflow files themselves with ActionLint
        run: actionlint
        shell: micromamba-shell {0}

      - name: Check environment files with YAMLLint
        run: yamllint ci/*.yml
        shell: micromamba-shell {0}

      - name: Install collection dependencies
        run: ansible-galaxy install -r requirements.yml
        shell: micromamba-shell {0}

      - name: Run ansible-lint
        run: ansible-lint -c .ansible-lint
        shell: micromamba-shell {0}
